Algoritmo "PG46EXER0A"
// Disciplina   : [Linguagem e Lógica de Programação com Js]
// Professor   : Obama, Jaja, Mestre Jailson Costa
// Descrição   : Tabuada de multiplicação (De 1 até 10)
// Autor(a)    : Deeniel
// Data atual  : 01/10/2024
Var
   num, i: inteiro


Inicio
   escreval("Digite um numero para ver a tabuada: ")
   leia(num)

   para i de 1 até 10 faça
      escreval(num, " x ", i, " = ", num * i)
   fimpara

Fimalgoritmo