Algoritmo "PG46EXER0H"
// Disciplina   : [Linguagem e Lógica de Programação com Js]
// Professor   : Obama, Jaja, Mestre Jailson Costa
// Descrição   : os valores de conversão de graus Celsius em Fahrenheit
// Autor(a)    : Deeniel
// Data atual  : 01/10/2024
Var
   C, F: real
   i: inteiro

inicio
   i := 10
   enquanto i <= 100 faca
      F := (i * 9 / 5) + 32
      escreval("Graus Celsius : ", i:0:1, " Graus Fahrenheit: ", F:0:1)
      i := i + 10
   fimenquanto
fimalgoritmo