Algoritmo "PG46EXER0B"
// Disciplina   : [Linguagem e Lógica de Programação com Js]
// Professor   : Obama, Jaja, Mestre Jailson Costa
// Descrição   : Soma dos 100 primeiros numeros inteiros
// Autor(a)    : Deeniel
// Data atual  : 01/10/2024
Var
   soma, i: inteiro
inicio
   soma := 0

   para i de 1 até 100 faça
      soma := soma + i
   fimpara

   escreval("A soma dos 100 primeiros números inteiros é: ", soma)
fimalgoritmo