Algoritmo "PG46EXER0E"
// Disciplina   : [Linguagem e Lógica de Programação com Js]
// Professor   : Obama, Jaja, Mestre Jailson Costa
// Descrição   : Apresentar os resultados das potências de 3
// Autor(a)    : Deeniel
// Data atual  : 01/10/2024
Var
   i: inteiro
   potencia: inteiro
inicio
   potencia := 1
   para i de 0 até 15 faça
      escreval("3 elevado a ", i, " é: ", potencia)
      potencia := potencia * 3
   fimpara
fimalgoritmo